name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 100.27.198.79 >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      env:
        EC2_USER: ubuntu
        EC2_HOST: ip-da-instancia
        EC2_KEY: ${{ secrets.EC2_KEY }}
        REMOTE_DIR: /var/www/seu-site
      run: |
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* $EC2_USER@$EC2_HOST:$REMOTE_DIR

    - name: Restart Nginx
      env:
        EC2_USER: ubuntu
        EC2_HOST: 100.27.198.79
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST 'sudo systemctl restart nginx'
